version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data: