name: Deploy to VPS

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root
            if [ ! -d collaborative_editor ]; then
              git clone https://github.com/IU-Capstone-Project-2025/mealix.git
            fi
            cd mealix
            git pull origin main
            docker compose down
            docker compose up --build -d
